apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  labels:
    app: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:9.9.4-community
        env:
        - name: SONAR_JDBC_URL
          value: jdbc:postgresql://postgres:5432/sonar
        - name: SONAR_JDBC_USERNAME
          value: sonar
        - name: SONAR_JDBC_PASSWORD
          value: sonar
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: sonar-volume
          mountPath: /opt/sonarqube/data
          subPath: data
        - name: sonar-volume
          mountPath: /opt/sonarqube/extensions
          subPath: extensions
        - name: sonar-volume
          mountPath: /opt/sonarqube/logs
          subPath: logs
      initContainers:
       - name: increase-vm-max-map
         image: busybox
         command: ['sysctl', '-w', 'vm.max_map_count=262144']
         securityContext:
           privileged: true
      volumes:
        - name: sonar-volume
          persistentVolumeClaim:
            claimName: sonar-pvc