apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: MY_ENV
      value: "Teste!"
  initContainers:
  - name: init-container
    image: busybox
    command: ['sh', '-c', 'echo "Configurando envs..."']
    
