apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nginx-role
  namespace: ingress
subjects:
- kind: ServiceAccount
  name: nginx
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: nginx-role
  apiGroup: rbac.authorization.k8s.ioi
