apiVersion: v1
kind: Pod
metadata:
  name: commands
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: commands
    image: debian
    command: ["tail"]
    args: ["-f", "/dev/null"]
  restartPolicy: OnFailure
